[package]
name = "rkusb"
version = "0.3.0"
edition = "2024"
authors = ["Tnze <Tnze@tnze.tech>"]
license = "GPL-2.0"
description = "Library and CLI tools for manipulating Rockchip devices"

[dependencies]
rkafp = "0.1.2"
clap = { version = "4.6", features = ["derive"] }
crc = "3.4"
env_logger = "0.11"
humantime = "2.3"
humansize = "2.1"
log = "0.4"
memmap2 = "0.9"
rusb = "0.9"
thiserror = "2.0"
zerocopy = { version = "0.8", features = ["derive", "simd"] }
rand = "0.10"
hex = "0.4"
rc4 = "0.2"
gpt = { version = "4.1", features = ["log"] }
